name: Freedom
version: '1.0-SNAPSHOT'
main: xyz.yaszu.freedom.Freedom
api-version: '1.21'
commands:
  openGui:
    description: "you can't see me"
    usage: "/openGui"
  opengui:
    description: "you can't see me"
    usage: "/openGui"
  trust:
    description: "With what?"
    usage: "/trust"
  fling:
    description: "Fling"
  ComorAction:
    description: "Baller"
  AbilityOne:
    description: "Executes Ability One"
  ally:
    description: "blah"
  revive:
    description: "Revive"
  Revive:
    description: "Revive"